using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace NetUnityApi.Responses.Multiplayer.Name
{
    public class NameResponse
    {
        [JsonPropertyName("id")] public string Id { get; set; }
        [JsonPropertyName("name")] public string Name { get; set; }
        [JsonPropertyName("autoGenerated")] public string AutoGenerated { get; set; }
    }

    public class NameRequest
    {
        public string name { get; set; }
    }
}
